// import Head from "next/head";

import BuyPage from "~/components/buy";
import Footer from "~/components/footer";
import HomePage from "~/components/home";
import LorePage from "~/components/lore";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className="bg-customBg flex min-h-screen flex-col items-center justify-center">
        <HomePage />
        <BuyPage />
        <LorePage />
      </main>
      <Footer />
    </>
  );
}
